name: custom deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages

    runs-on: ubuntu-latest

    steps:
      # 1) リポジトリのコードをチェックアウト
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Node.js環境をセットアップ（バージョンはお好みで）
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3) 依存パッケージをインストール
      - name: Install dependencies
        run: npm ci
        
      # 3.3) vite をプロジェクトの依存関係としてインストール
      - name: Install vite as a project dependency
        run: npm install vite

      # 3.5) vite をグローバルにインストール
      - name: Install vite globally
        run: npm install -g vite

      # 3.75) キャッシュをクリア
      - name: Clear cache
        run: rm -rf node_modules

      # 4) ビルドコマンド (package.json の "build": "vite build" を想定)
      - name: Build
        run: npm run build

      # 5) ビルド成果物(distフォルダ)をアップロード
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2 # v2に更新
        with:
          path: './dist'

      # 6) GitHub Pagesにデプロイ
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2 # v2に更新
