{
  "name": "my-lp",
  "version": "1.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build", // この部分を確認・修正
    "preview": "vite preview"
  },
  "dependencies": {
    // ...
  },
  "devDependencies": {
    // ...
  }
}
